{
 "title": "Pizza Shop - RED",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(pizza_http_requests_total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(pizza_orders_total{status=\"failed\"}[5m]))\r\n/\r\nsum(rate(pizza_orders_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (rate(pizza_http_request_duration_seconds_bucket{service=\"gateway\"}[5m])))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}